apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 541102295347.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 541102295347.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 5f714086
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
